### ISSUE TITLE
[BUG] "data/TobySolutions/testimonials/loftwah.json" file already modified before changing

### ISSUE THREAD

**Issue by vrushabhgawas14** [EddieHubCommunity/BioDrop#10151]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

"data/TobySolutions/testimonials/loftwah.json"

### Version of BioDrop (for example "v1.2.3")

v2.99.4

### Description

```data/TobySolutions/testimonials/loftwah.json``` file comes with some modification even after cloning.
(Not sure if it is only happening to me.)

### Steps to Reproduce

Clone **BioDrop** repo in your terminal (mine is VS Code) 
```git
git clone git@github.com:Your-UserName/BioDrop.git
```
and check the status by 
```git
git status
```

### Screenshots

![terminal](https://github.com/EddieHubCommunity/BioDrop/assets/126388189/60808e28-4e09-4ba6-a4bf-4bf51dec10b0)

### Do you want to work on this issue?

No

**Comment by kumarsonsoff3** [comment]
It's these two files ([TobySolutions/testimonials/loftwah.json](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/TobySolutions/testimonials/loftwah.json) & [tobySolutions/testimonials/loftwah.json](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/tobySolutions/testimonials/loftwah.json)) causing this issue because Git is considering these both as a same file while GitHub is case specific. 

A solution to this could be to let @tobySolutions decide which of these testimonials from loftwah you want to keep & delete the other one. If you wanted to keep the recent one ([1st one](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/TobySolutions/testimonials/loftwah.json)), you should move it [here](https://github.com/EddieHubCommunity/BioDrop/tree/main/data/tobySolutions/testimonials) and delete the one existed there.

@tobySolutions, Please comment below so I can assign this to you because no one else is allowed to edit someone else data files. You should create a PR fixing these soon as it could lead to confusion for new contributors!

Feel free to reach out if you need any help with this!

**Comment by vrushabhgawas14** [comment]
> It's these two files ([TobySolutions/testimonials/loftwah.json](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/TobySolutions/testimonials/loftwah.json) & [tobySolutions/testimonials/loftwah.json](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/tobySolutions/testimonials/loftwah.json)) causing this issue because Git is considering these both as a same file while GitHub is case specific.
> 
> A solution to this could be to let **tobySolutions** decide which of these testimonials from **loftwah** you want to keep & delete the other one. If you wanted to keep the recent one ([1st one](https://github.com/EddieHubCommunity/BioDrop/blob/main/data/TobySolutions/testimonials/loftwah.json)), you should move it [here](https://github.com/EddieHubCommunity/BioDrop/tree/main/data/tobySolutions/testimonials) and delete the one existed there.
> 
> @tobySolutions, Please comment below so I can assign this to you because no one else is allowed to edit someone else data files. Then you should create a PR fixing these soon as it could lead to confusion for new contributors!
> 
> Feel free to reach out if you need any help with this!

Ok so it is not a bug or problem from contributors side, well Thanks!

**Comment by eddiejaoude** [comment]
The folder got renamed with only a case change, the actual final (single) file path is here `data/TobySolutions/testimonials/loftwah.json`

https://github.com/EddieHubCommunity/BioDrop/tree/main/data/TobySolutions/testimonials

Your file system or git is setup in non case sensitive mode
