### ISSUE TITLE
[FEATURE] Improve accessibility of Event Cards

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#7144]
### Description

This issue came from a discussion with @EmmaDawsonDev who made the observation that our event cards could be improved for accessibility 

Some concerns:
The hover effect on desktop/card depression on mobile are not ideal for accessibility and can increase how verbose the screen reader output is.

Please see this resource to first understand accessibility approaches in cards: https://inclusive-components.design/cards/

Add to the discussion in the comments and once a path has been decided, can move to ready for dev

**Comment by akash19coder** [comment]
I wanna work on this issue could please assign it to me?

**Comment by shoebilyas123** [comment]
The main issue I notice is that the main content in the events card is wrapped inside the <a> tag which causes accessibility issues. I tested it with the Orca screen reader in ubuntu and it really sounds verbose to point that it is difficult to comprehend in my opinion. 
I read the resource, I suggest we can use a tag instead of p tag for the title  and use div instead of a tag on the main content. Then we can redirect any clicks on the card on the card to the link. Finally we can add aria-describedby method there also.

**Comment by akash19coder** [comment]
@shoebilyas123 are you referring to the pseudo-content trick mentioned in the resource? 🙂

**Comment by shoebilyas123** [comment]
Yes I am referring to that particular trick.

**Comment by shoebilyas123** [comment]
> @shoebilyas123 are you referring to the pseudo-content trick mentioned in the resource? 🙂

Yes I am referring to that particular trick.

**Comment by akash19coder** [comment]
Maybe we should also remove unnecessary tab stops from the pages.

**Comment by shoebilyas123** [comment]
> Maybe we should also remove unnecessary tab stops from the pages.

Can you please elaborate on what tab stops are?

**Comment by SaraJaoude** [comment]
As this will be redesigned in the near future I will close this for now.
