### ISSUE TITLE
[BUG] Images overflowing on events with json docs

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9289]
### Description

Navigate to [Events with json docs]( https://www.biodrop.io/docs/how-to-guides/events-json)
Scroll to the right
see that there are images overflowing past the page

Edit: NOTE - this does not happen on mobile, only on desktop/laptop view

Screenshot
![bug-events-with-json](https://github.com/EddieHubCommunity/BioDrop/assets/97615019/5f786de8-f732-4832-a3c7-97da8c226c66)

### Do you want to work on this issue?

None

**Comment by ChinmayMhatre** [comment]
Tested it issue exists on my system as well

**Comment by PradeepG-07** [comment]
Please assign me this issue

**Comment by ChinmayMhatre** [comment]
@PradeepG-07  assigned you the issue

**Comment by PradeepG-07** [comment]
Hi @ChinmayMhatre I have made a PR. Please verify it. Thank You.

**Comment by PradeepG-07** [comment]
A Kind request from me to add hacktoberfest label which help me a lot. Please.

**Comment by amandamartin-dev** [comment]
> A Kind request from me to add hacktoberfest label which help me a lot. Please.

Done

**Comment by SaraJaoude** [comment]
@PradeepG-07 in a matter of a few hours you have chased two maintainers to review your PR.  Whilst I understand this is probably because you are excited about Hacktoberfest, this is an unreasonable request.  Please do not tag specific maintainers and also as previously mentioned to you please do not create excess notifications.  One of the maintainers will review your PR when they can - we are going through PRs and there are several that have been created before yours. 

Please remember that maintainers are volunteers and have other work and personal commitments.

**Comment by PradeepG-07** [comment]
Sorry for what I have done. I will never repeat it again

**Comment by Rohithkumar77** [comment]
Assigin me the issues i can slove themmm

**Comment by eddiejaoude** [comment]
@Rohithkumar77 the issue has been completed, please check the status and assignment first
