### ISSUE TITLE
[DOCS] Missing clarity and confidence in wording

### ISSUE THREAD

**Issue by Shashmit** [EddieHubCommunity/BioDrop#9422]
### Description

I would like to propose a few changes in the document. Some of the lines lack clarity and occasionally appear informal, so I would like to improve the grammar and make some tweaks.
Changes Like :

- The Social Shortcut will then be displayed on your profile using your custom URL.
- When adding or editing a link, to have it appear at the top of your profile, please turn on the toggle at the bottom of the form.
- Please note that this must be one of your URL links and should use the same icon as your link.

Lines like these improves the overall readability of the documentation .

### Screenshots

<img width="980" alt="Screenshot 2023-10-09 at 03 28 22" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/91978655-1665-4d4b-8f77-1a7cb460bf3e">
<img width="980" alt="Screenshot 2023-10-09 at 03 28 30" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/eeb9fd50-2e02-48b5-9ad9-cfd97017f2c5">
<img width="980" alt="Screenshot 2023-10-09 at 03 29 42" src="https://github.com/EddieHubCommunity/BioDrop/assets/70282239/4c596c68-147e-4f20-8d6f-466a8a0aab1f">

### Do you want to work on this issue?

Yes

**Comment by SaraJaoude** [comment]
Thank you for raising. 

The informal and colloquial language used in our Docs has been done on purpose to reflect how we speak in the EddieHub community.  Your proposed changes also do not keep to the style we have used - the use of the capitalisation in words such as Profile and Forms are intentional given that these are BioDrop terms. 

As we cannot see that your proposed changes actually improve the interpretation of the Docs (but are simply another way of writing them), I will close this issue. 

When raising an issue please also consider using an up to date version of the app - the screenshots you have used date back from June 2023 (and major changes have been made since then).
