### ISSUE TITLE
[FEATURE] Hover color for links on open source roadmap

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/BioDrop#9471]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

On the open source roadmap page, it is not immediately clear to a sighted user that the roadmap steps are links to subsequent pages. 

This issue is to add a color on hover (dark and light mode) to enhance discoverability of these pages.

Page: https://www.biodrop.io/docs/open-source-roadmap

### Description

add hover CSS to the links as described above - they should remain consistent with the style of hover colors throughout the project

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Great suggestion Amanda 👍

**Comment by HardikChoudhary24** [comment]
Please assign this issue to me

**Comment by akkshitgupta** [comment]
please assign me this issue.

**Comment by aryansri-19** [comment]
Hey, can you please assign this to me?

**Comment by dark-developer15** [comment]
I would like to address the issue too. @amandamartin-dev

**Comment by nayakswadhin** [comment]
@eddiejaoude I have raised a PR on this issue. Kindly Review it.

**Comment by balaraju-nerati** [comment]
@amandamartin-dev I wanted to work on this issue, so I mentioned this in discord too.....please assign this to me😶, this would be my first contribution😀

**Comment by eddiejaoude** [comment]
What is going on here? This is not collaboration 😢 - please read the [contributing guide](https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md) before commenting (note: that tagging maintainers or commenting in Discord or raising a pull request before it is assigned does not improve the chances of getting assigned)

@HardikChoudhary24 you were the first to request the issue plus as this looks like your first contribution to the project and this issue is a "good **first** issue" I have assigned it to you
