### ISSUE TITLE
[BUG] Icon copy notification text is not readable as the underlying elements are also visible.

### ISSUE THREAD

**Issue by mrinmay7875** [EddieHubCommunity/BioDrop#9618]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production on biodrop.io

### Version of BioDrop (for example "v1.2.3")

latest version

### Description

In the icons page when we click on the icons then that icons gets copied and we see a toast notification on the right side of the screen. However, the toast notification alert is not solid and hence the underlying elements are not showing visible through the notification and hence the text written in the notification is often not readable properly.

I am attaching a screenshot below.

I think if we can have a solid toast notification that will be better in my opinion. 

### Screenshots

![image](https://github.com/EddieHubCommunity/BioDrop/assets/33797909/fda6ab1a-7709-4a41-84a0-9e268b7323eb)

### Do you want to work on this issue?

No

**Comment by SaraJaoude** [comment]
We cannot seem to replicate this so I will add the `talk: discussion` label for now. 

One of the things to ascertain is what browser is this appearing in? 

@mrinmay7875 please can you edit the description to the version **number** (saying "latest" can be confusing).

**Comment by mrinmay7875** [comment]
@SaraJaoude  See that after select on the icon we see this notification where text is not readable properly because the navbar button is showing through the notification.<img width="706" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/33797909/9cb1c4b3-a2be-4ff4-b380-aaa2744176cf">

Also when we hover over the notification then we see the navbar button is showing up.
<img width="506" alt="image" src="https://github.com/EddieHubCommunity/BioDrop/assets/33797909/a0c5ff46-76bb-48b2-b629-85a8ab1ab2ff">

**Comment by anirudhp26** [comment]
Yes, I am also facing the same issue when I tried replicating it

**Comment by anirudhp26** [comment]
If this is ready to be fixed then I would like to work on this :)

**Comment by mrinmay7875** [comment]
@SaraJaoude Let me know if you are able to reproduce this issue or have any further questions.

**Comment by sital002** [comment]
The bug does exist here is the screenshot for it 
![image](https://github.com/EddieHubCommunity/BioDrop/assets/93700622/cf3acca4-697d-47ef-8ed1-bf3ebf14d946)

Tested on :
Browser: Mozilla Firefox and Chrome
OS: Ubuntu 

@mrinmay7875  If you want to work on the issue please mention that on the issue description since you have already created a PR for it. Please familiarize yourself with our contributing guidelines https://github.com/EddieHubCommunity/BioDrop/blob/main/CONTRIBUTING.md and don't tag specific maintainers.

**Comment by SaraJaoude** [comment]
@mrinmay7875 it is unclear as to whether you want to work on this issue or not - but given your comments in your previous PR I am going to assume that you do, so that I will assign this to you.  

As Sital mentioned please make it clearer in future if you do want to work on an issue as this avoids confusion for both maintainers and other contributors.

**Comment by mrinmay7875** [comment]
Thanks for assigning the issue to me, Yes I will work on this issue and create a PR asap

**Comment by SaraJaoude** [comment]
> Can I take up the issue? As @mrinmay7875 is not having time at the moment and he is okay that I can take up the Issue 

@Kamaruddheen I have assigned this to you - please also see my comments here: https://github.com/EddieHubCommunity/BioDrop/pull/9652#issuecomment-1793472448

**Comment by Kamaruddheen** [comment]
Got Sara, Will work on new PR.
